### ISSUE TITLE
Предварительная оценка (по вопросам в тг - @rendizi) 

### ISSUE THREAD

**Issue by abglnv** [s0vunia/project2sprint#1]
- Существует Readme документ, в котором описано, как запустить систему и как ей пользоваться. 10/10
- Программа запускается и все примеры с вычислением арифметических выражений корректно работают 10/10
- Программа запускается и выполняются произвольные примеры с вычислением арифметических выражений 10/10
- Можно перезапустить любой компонент системы и система корректно обработает перезапуск (результаты сохранены, система продолжает работать) 10/10
- Система предосталяет графический интерфейс для вычисления арифметических выражений 0/10
- Реализован мониторинг воркеров 20/20
- Реализован интерфейс для мориторинга воркеров 0/10
- Вам понятна кодовая база и структура проекта 10/10
- У системы есть документация со схемами, которая наглядно отвечает на вопрос: "Как это все работает 10/10
- Выражение должно иметь возможность выполняться разными агентами 10/10
<h1>Total: 90/110</h1>

**Comment by s0vunia** [comment]
**Благодарю за оценку!**
